version: '3.3'

services:
  database:
    env_file:
      - .env
    image: 'postgres'
    volumes:
      - db-data:/var/lib/posgresql/data
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:5432

volumes:
  db-data:
